{% set name = "editables" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/editables-{{ version }}.tar.gz
  sha256: 309627d9b5c4adc0e668d8c6fa7bac1ba7c8c5d415c2d27f60f081f8e80d1de2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.3
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - editables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pfmoore/editables
  summary: Editable installations
  dev_url: https://github.com/pfmoore/editables
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
    - ofek
